/* CreateAccountUI - a UI for users to create a new account
 * 
 * Update for Use Case Extensions
 *  Added the security pass phrase sections to the UI and the requirement that
 * those fields be filled in to accept a new account.
 */
package mylocalpolitics.presentation;

import mylocalpolitics.service.*;
import mylocalpolitics.domain.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Nels Haugen
 * @version 2
 */
public class CreateAccountUI extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccount
     */
    public CreateAccountUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameFld = new javax.swing.JTextField();
        firstNameLbl = new javax.swing.JLabel();
        lastNameLbl = new javax.swing.JLabel();
        lastNameFld = new javax.swing.JTextField();
        passwordLbl = new javax.swing.JLabel();
        emailFld = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        createBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        confirmPasswordLbl = new javax.swing.JLabel();
        passwordFld = new javax.swing.JPasswordField();
        confirmPasswordFld = new javax.swing.JPasswordField();
        authCodeLbl = new javax.swing.JLabel();
        authCodeFld = new javax.swing.JTextField();
        passPhraseBox = new javax.swing.JComboBox<>();
        passPhraseFld = new javax.swing.JTextField();
        passPhraseLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstNameFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFldActionPerformed(evt);
            }
        });

        firstNameLbl.setText("First Name");

        lastNameLbl.setText("Last Name");

        lastNameFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFldActionPerformed(evt);
            }
        });

        passwordLbl.setText("Password");

        emailFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFldActionPerformed(evt);
            }
        });

        emailLbl.setText("Email");

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLbl.setText("Create Account");

        createBtn.setText("Ok");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        confirmPasswordLbl.setText("Confirm Password");

        authCodeLbl.setText("Authenticator code");

        authCodeFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authCodeFldActionPerformed(evt);
            }
        });

        passPhraseBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What was the name of your first pet?", "What was the name of your high school?", "What is your mother's maiden name?", "Name the hospital were you born in?" }));

        passPhraseLbl.setText("Security Passphrase:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordLbl)
                                    .addComponent(lastNameLbl)
                                    .addComponent(emailLbl)
                                    .addComponent(firstNameLbl)
                                    .addComponent(authCodeLbl)
                                    .addComponent(confirmPasswordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(passPhraseLbl))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(passPhraseBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameFld, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(confirmPasswordFld)
                            .addComponent(emailFld, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(firstNameFld, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(passwordFld, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(passPhraseFld)
                            .addComponent(authCodeFld))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameLbl)
                    .addComponent(firstNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLbl)
                    .addComponent(lastNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLbl)
                    .addComponent(emailFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPasswordLbl)
                    .addComponent(confirmPasswordFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authCodeLbl)
                    .addComponent(authCodeFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(passPhraseLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passPhraseBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passPhraseFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(createBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFldActionPerformed

    private void emailFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFldActionPerformed

    private void lastNameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFldActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelBtnActionPerformed
    
    /**
     * Event activated when user clicks the create button. Assigns them a login, 
     * ensures that all fields are filled out, confirms that both password 
     * entries match, and attaches their login to a new account. Creates a new
     * account implementation and takes them to the LoginUI screen.
     */
    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        Login login = new Login();
        login.setUsername(emailFld.getText());
        login.setPassword(new String(passwordFld.getPassword()));
        login.setPassPhrase(passPhraseFld.getText());
        System.out.println(passPhraseFld.getText());
        login.setPassOption(passPhraseBox.getSelectedIndex());
        System.out.println(passPhraseBox.getSelectedIndex());
        
        if (!login.validate()) {
            JOptionPane.showMessageDialog(this, "Must supply a username, password,"
                    + " and passphrase", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String confirmPassword = new String(confirmPasswordFld.getPassword());
        if (!confirmPassword.equals(login.getPassword())) {
            JOptionPane.showMessageDialog(this, "Passwords don't match; try again", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Account account = new Account();
        account.setFirstName(firstNameFld.getText());
        account.setLastName(lastNameFld.getText());
        account.setLogin(login);
        boolean isValid = account.validate();
        if (!isValid) {
            JOptionPane.showMessageDialog(this, "Must supply first and last names", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            // all fields are complete; create account
            AccountSvcCacheImpl impl = AccountSvcCacheImpl.getInstance();
            account = impl.create(account);
            String authCode = authCodeFld.getText();
            // code for authenticators provided by admin
            if (authCode.equals("password")) {
                account.setAuthenticator(true);
            }
            JOptionPane.showMessageDialog(this, "Congratulations, your account has been created",
                    "Account created", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            LoginUI loginUI = new LoginUI();
            loginUI.setVisible(true);
        }
    }//GEN-LAST:event_createBtnActionPerformed

    private void authCodeFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authCodeFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authCodeFldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccountUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccountUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccountUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccountUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccountUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authCodeFld;
    private javax.swing.JLabel authCodeLbl;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPasswordField confirmPasswordFld;
    private javax.swing.JLabel confirmPasswordLbl;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField emailFld;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField firstNameFld;
    private javax.swing.JLabel firstNameLbl;
    private javax.swing.JTextField lastNameFld;
    private javax.swing.JLabel lastNameLbl;
    private javax.swing.JComboBox<String> passPhraseBox;
    private javax.swing.JTextField passPhraseFld;
    private javax.swing.JLabel passPhraseLbl;
    private javax.swing.JPasswordField passwordFld;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
