/* EditMenuUI - a UI for editing information about politicians that have already 
 * been added
 */
package mylocalpolitics.presentation;

import javax.swing.JOptionPane;
import mylocalpolitics.service.*;
import mylocalpolitics.domain.*;

/**
 *
 * @author Nels Haugen
 * @version 1
 */
public class EditMenuUI extends javax.swing.JFrame {

    private int row = -1;

    /**
     *
     * @param row - the current row, used to keep track of which politician in 
     * the list has been selected.
     */
    public void setRow(int row) {
        this.row = row;
    }
    
    private Account account = null;

    /**
     *
     * @param account - Account object
     */
    public void setAccount(Account account) {
        this.account = account;
    }
    
    /**
     *
     * @param politician - Politician object
     */
    public void setEditFields(Politician politician) {
        firstNameFld.setText(politician.getFirstName());
        lastNameFld.setText(politician.getLastName());
        officeFld.setText(politician.getOffice());
        stateFld.setText(politician.getState());
        districtFld.setText(politician.getDistrict());
    }
    
    /**
     * Creates new form EditMenu
     */
    public EditMenuUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        firstNameLbl = new javax.swing.JLabel();
        lastNameLbl = new javax.swing.JLabel();
        officeLbl = new javax.swing.JLabel();
        stateLbl = new javax.swing.JLabel();
        districtLbl = new javax.swing.JLabel();
        firstNameFld = new javax.swing.JTextField();
        lastNameFld = new javax.swing.JTextField();
        officeFld = new javax.swing.JTextField();
        stateFld = new javax.swing.JTextField();
        districtFld = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Edit/Create Politician");

        firstNameLbl.setText("First Name");

        lastNameLbl.setText("Last Name");

        officeLbl.setText("Office");

        stateLbl.setText("State");

        districtLbl.setText("District");

        submitBtn.setText("Submit Changes");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitBtn)
                        .addGap(18, 18, 18)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(firstNameLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(firstNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(districtLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stateLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(officeLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lastNameLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastNameFld)
                                    .addComponent(officeFld)
                                    .addComponent(stateFld)
                                    .addComponent(districtFld))))
                        .addGap(0, 202, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLbl)
                    .addComponent(firstNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLbl)
                    .addComponent(lastNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(officeLbl)
                    .addComponent(officeFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateLbl)
                    .addComponent(stateFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(districtLbl)
                    .addComponent(districtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(submitBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt - activated when the submit button is pressed.
     *  updates the new information for the politician and adds it to the list
     * to be verified by authenticators.
     */
    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        String firstName = firstNameFld.getText();
        String lastName = lastNameFld.getText();
        String office = officeFld.getText();
        String state = stateFld.getText();
        String district = districtFld.getText();
        
        Politician politician = new Politician(firstName, lastName, office, state,
        district);
        
        boolean isValid = politician.validate();
        if (!isValid) {
            JOptionPane.showMessageDialog(this, 
                    "All fields are required", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (row >= 0) {
            Politician edit = account.getPoliticians().get(row);
            edit.setFirstName(firstName);
            edit.setLastName(lastName);
            edit.setOffice(office);
            edit.setState(state);
            edit.setDistrict(district);
            
            // add to list for authenticator to verify
            Politician.addToAuthList(politician);
            JOptionPane.showMessageDialog(this, "Your Politician has been saved",
                "Saved Politician", JOptionPane.INFORMATION_MESSAGE);
        
            // clear fields
            firstNameFld.setText("");
            lastNameFld.setText("");
            officeFld.setText("");
            stateFld.setText("");
            districtFld.setText("");
        
            this.setVisible(false);
            MainMenuUI mainMenuUI = new MainMenuUI();
            mainMenuUI.setAccount(account);
            mainMenuUI.setVisible(true);
        } else {
            // add the contact to the account and persist it using the service
            account.add(politician);
            IAccountSvc impl = AccountSvcCacheImpl.getInstance();
            account = impl.update(account);
            if (account == null) {
                JOptionPane.showMessageDialog(this,
                    "Your Contact was not saved; please try again", "Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
        
            // add to list for authenticator to verify
            Politician.addToAuthList(politician);
            JOptionPane.showMessageDialog(this, "Your new Politician has been saved",
                "Saved Politician", JOptionPane.INFORMATION_MESSAGE);
        
            // clear fields
            firstNameFld.setText("");
            lastNameFld.setText("");
            officeFld.setText("");
            stateFld.setText("");
            districtFld.setText("");
        
            this.setVisible(false);
            MainMenuUI mainMenuUI = new MainMenuUI();
            mainMenuUI.setAccount(account);
            mainMenuUI.setVisible(true);
        }
        
    }//GEN-LAST:event_submitBtnActionPerformed

    /**
     * 
     * @param evt - activates when the cancel button is clicked.
     */
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.setVisible(false);
        MainMenuUI mainMenuUI = new MainMenuUI();
        mainMenuUI.setAccount(account);
        mainMenuUI.setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditMenuUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField districtFld;
    private javax.swing.JLabel districtLbl;
    private javax.swing.JTextField firstNameFld;
    private javax.swing.JLabel firstNameLbl;
    private javax.swing.JTextField lastNameFld;
    private javax.swing.JLabel lastNameLbl;
    private javax.swing.JTextField officeFld;
    private javax.swing.JLabel officeLbl;
    private javax.swing.JTextField stateFld;
    private javax.swing.JLabel stateLbl;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
